package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// mcpJSON represents the .mcp.json format used by Claude Code.
type mcpJSON struct {
	MCPServers map[string]mcpServerEntry `json:"mcpServers"`
}

type mcpServerEntry struct {
	Type    string            `json:"type"`
	Command string            `json:"command"`
	Args    []string          `json:"args"`
	Env     map[string]string `json:"env"`
	URL     string            `json:"url"`
}

// mcpxConfig mirrors config.Config for YAML output with comments.
type mcpxConfig struct {
	Servers map[string]*mcpxServerConfig `yaml:"servers"`
}

type mcpxServerConfig struct {
	Command        string            `yaml:"command"`
	Args           []string          `yaml:"args,omitempty"`
	Transport      string            `yaml:"transport"`
	Env            map[string]string `yaml:"env,omitempty"`
	URL            string            `yaml:"url,omitempty"`
	Daemon         bool              `yaml:"daemon,omitempty"`
	StartupTimeout string            `yaml:"startup_timeout,omitempty"`
}

func initCmd() *cobra.Command {
	var (
		inputPath  string
		outputPath string
		force      bool
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Import .mcp.json into .mcpx/config.yml",
		Long:  "Reads a .mcp.json file (Claude Code format) and generates a .mcpx/config.yml for mcpx.",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Find .mcp.json if not specified.
			if inputPath == "" {
				cwd, err := os.Getwd()
				if err != nil {
					return fmt.Errorf("getwd: %w", err)
				}
				inputPath = filepath.Join(cwd, ".mcp.json")
			}

			data, err := os.ReadFile(inputPath)
			if err != nil {
				return fmt.Errorf("read %s: %w", inputPath, err)
			}

			var mcp mcpJSON
			if err := json.Unmarshal(data, &mcp); err != nil {
				return fmt.Errorf("parse %s: %w", inputPath, err)
			}

			if len(mcp.MCPServers) == 0 {
				return fmt.Errorf("no servers found in %s", inputPath)
			}

			// Convert to mcpx config.
			cfg := convertMCPJSON(&mcp)

			// Determine output path.
			if outputPath == "" {
				cwd, err := os.Getwd()
				if err != nil {
					return fmt.Errorf("getwd: %w", err)
				}
				outputPath = filepath.Join(cwd, ".mcpx", "config.yml")
			}

			// Check if output already exists.
			if !force {
				if _, err := os.Stat(outputPath); err == nil {
					return fmt.Errorf("%s already exists (use --force to overwrite)", outputPath)
				}
			}

			// Ensure directory exists.
			dir := filepath.Dir(outputPath)
			if err := os.MkdirAll(dir, 0755); err != nil {
				return fmt.Errorf("create directory %s: %w", dir, err)
			}

			// Marshal to YAML.
			out, err := yaml.Marshal(cfg)
			if err != nil {
				return fmt.Errorf("marshal config: %w", err)
			}

			// Write with a header comment.
			header := "# Generated by mcpx init from " + filepath.Base(inputPath) + "\n# See: mcpx --help\n\n"
			if err := os.WriteFile(outputPath, []byte(header+string(out)), 0644); err != nil {
				return fmt.Errorf("write %s: %w", outputPath, err)
			}

			// Print summary.
			fmt.Printf("Imported %d server(s) from %s\n", len(cfg.Servers), inputPath)
			for name, sc := range cfg.Servers {
				fmt.Printf("  %s → %s (%s)\n", name, sc.Command, sc.Transport)
			}
			fmt.Printf("\nConfig written to %s\n", outputPath)
			fmt.Println("Test with: mcpx list")

			return nil
		},
	}

	cmd.Flags().StringVar(&inputPath, "from", "", "Path to .mcp.json (default: ./.mcp.json)")
	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "Output path (default: ./.mcpx/config.yml)")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite existing config")

	return cmd
}

// convertMCPJSON transforms a .mcp.json structure into an mcpx config.
func convertMCPJSON(mcp *mcpJSON) *mcpxConfig {
	cfg := &mcpxConfig{
		Servers: make(map[string]*mcpxServerConfig),
	}

	for name, entry := range mcp.MCPServers {
		sc := &mcpxServerConfig{
			Command: entry.Command,
			Args:    entry.Args,
		}

		// Determine transport.
		switch entry.Type {
		case "streamable-http", "http":
			sc.Transport = "http"
			sc.URL = entry.URL
		case "sse":
			sc.Transport = "sse"
			sc.URL = entry.URL
		default:
			sc.Transport = "stdio"
			sc.Daemon = true
			sc.StartupTimeout = "30s"
		}

		// Copy env, skip empty maps.
		if len(entry.Env) > 0 {
			sc.Env = entry.Env
		}

		cfg.Servers[name] = sc
	}

	return cfg
}
